### ISSUE TITLE
MIDIが使えない場合におちる

### ISSUE THREAD

**Issue by nariakiiwatani** [jins-meme/JinsMemeBRIDGE-Android#22]
起動 -> MIDI Config -(アラート)-(OK)-> 戻るボタンでアプリが落ちる
08900362794c84b1e2b0b37da22fdee5d6dfba13 で確認

>05-24 06:29:28.732 22232-22232/com.jins_meme.bridge E/InputEventSender: Exception dispatching finished signal.
05-24 06:29:28.732 22232-22232/com.jins_meme.bridge E/MessageQueue-JNI: Exception in MessageQueue callback: handleReceiveCallback
05-24 06:29:28.733 22232-22232/com.jins_meme.bridge E/MessageQueue-JNI: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jins_meme.bridge.MemeMIDI.closePort()' on a null object reference
                                                                            at com.jins_meme.bridge.MIDIConfigFragment.onDetach(MIDIConfigFragment.java:78)
                                                                            at android.support.v4.app.Fragment.performDetach(Fragment.java:2444)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1448)
                                                                            at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                            at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:803)
                                                                            at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2360)
                                                                            at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                            at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                            at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:823)
                                                                            at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:776)
                                                                            at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:178)
                                                                            at com.jins_meme.bridge.MainActivity.onBackPressed(MainActivity.java:592)
                                                                            at android.app.Activity.onKeyUp(Activity.java:2477)
                                                                            at android.view.KeyEvent.dispatch(KeyEvent.java:2664)
                                                                            at android.app.Activity.dispatchKeyEvent(Activity.java:2730)
                                                                            at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:541)
                                                                            at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
                                                                            at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
                                                                            at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4127)
                                                                            at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4089)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                            at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                            at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                            at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                            at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                            at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3820)
                                                                            at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3981)
                                                                            at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2253)
                                                                            at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1874)
                                                                            at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1865)
                                                                            at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2230)
                                                                            at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                                            at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                            at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                            at android.os.Looper.loop(Looper.java:135)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
05-24 06:29:28.733 22232-22232/com.jins_meme.bridge D/AndroidRuntime: Shutting down VM
05-24 06:29:28.733 22232-22232/com.jins_meme.bridge E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.jins_meme.bridge, PID: 22232
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'void com.jins_meme.bridge.MemeMIDI.closePort()' on a null object reference
                                                                          at com.jins_meme.bridge.MIDIConfigFragment.onDetach(MIDIConfigFragment.java:78)
                                                                          at android.support.v4.app.Fragment.performDetach(Fragment.java:2444)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1448)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                          at android.support.v4.app.BackStackRecord.executePopOps(BackStackRecord.java:803)
                                                                          at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2360)
                                                                          at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                          at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                          at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:823)
                                                                          at android.support.v4.app.FragmentManagerImpl.popBackStackImmediate(FragmentManager.java:776)
                                                                          at android.support.v4.app.FragmentActivity.onBackPressed(FragmentActivity.java:178)
                                                                          at com.jins_meme.bridge.MainActivity.onBackPressed(MainActivity.java:592)
                                                                          at android.app.Activity.onKeyUp(Activity.java:2477)
                                                                          at android.view.KeyEvent.dispatch(KeyEvent.java:2664)
                                                                          at android.app.Activity.dispatchKeyEvent(Activity.java:2730)
                                                                          at android.support.v7.app.AppCompatActivity.dispatchKeyEvent(AppCompatActivity.java:541)
                                                                          at android.support.v7.view.WindowCallbackWrapper.dispatchKeyEvent(WindowCallbackWrapper.java:59)
                                                                          at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.dispatchKeyEvent(AppCompatDelegateImplBase.java:319)
                                                                          at com.android.internal.policy.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:2310)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.processKeyEvent(ViewRootImpl.java:4127)
                                                                          at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4089)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                          at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
                                                                          at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
                                                                          at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
                                                                          at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
                                                                          at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3820)
                                                                          at android.view.ViewRootImpl$ImeInputStage.onFinishedInputEvent(ViewRootImpl.java:3981)
                                                                          at android.view.inputmethod.InputMethodManager$PendingEvent.run(InputMethodManager.java:2253)
                                                                          at android.view.inputmethod.InputMethodManager.invokeFinishedInputEventCallback(InputMethodManager.java:1874)
                                                                          at android.view.inputmethod.InputMethodManager.finishedInputEvent(InputMethodManager.java:1865)
                                                                          at android.view.inputmethod.InputMethodManager$ImeInputEventSender.onInputEventFinished(InputMethodManager.java:2230)
                                                                          at android.view.InputEventSender.dispatchInputEventFinished(InputEventSender.java:141)
                                                                          at android.os.MessageQueue.nativePollOnce(Native Method)
                                                                          at android.os.MessageQueue.next(MessageQueue.java:323)
                                                                          at android.os.Looper.loop(Looper.java:135)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                      	at com.android.internal.os.ZygoteI
05-24 06:29:30.624 22232-22232/? I/Process: Sending signal. PID: 22232 SIG: 9

**Comment by tkrworks** [comment]
報告ありがとうございます。
こちらでも再現出来ましたので、調査・修正しまっす。
