### ISSUE TITLE
カメラ機能で撮ったデータの保存

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#25]
現状、保存されるファイル名が「pic.jpg」で、同名のファイルがあると上書きされるようなので、タイムスタンプを付けるなどして上書きされないようにしたいです。
また、データの保存先がアプリ固有の場所なのでGoogle純正のフォトアプリですぐ見れるようにしておきたいです。

**Comment by nariakiiwatani** [comment]
よくあるandroidアプリだと、保存先を本体かSDカードか選べる感じですよね。
CameraConfigFragmentを追加して設定するようにする方針で良いですか？

**Comment by tkrworks** [comment]
はい、それで良いと思いますー！

**Comment by nariakiiwatani** [comment]
http://blog.lciel.jp/blog/2014/02/08/android-about-storage/
https://akira-watson.com/android/external-storage-file.html
選択できるというのはむかしむかしの仕様だったようで、最近はプログラマにすら選ばせないことになっているようですね。
ということでそんな風に修正しようと思います。

**Comment by nariakiiwatani** [comment]
ad36042221fc5182625406deae25d5ea7550c607
修正しましt

**Comment by tkrworks** [comment]
確認したところ、「TAKE A PICTURE」をタップしたときに下記の例外で落ちてします。

06-22 20:26:17.035 17785-18160/com.jins_meme.bridge E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
                                                                      Process: com.jins_meme.bridge, PID: 17785
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.io.File.getName()' on a null object reference
                                                                          at com.example.android.camera2basic.Camera2BasicFragment$7.onCaptureCompleted(Camera2BasicFragment.java:899)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                                                                          at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by nariakiiwatani** [comment]
7374ff9c95cf0801dd6408b9c13699740908d5d3
同じエラーは再現できなかったのですが、権限が足りない場合に落ちるバグがあったのでそちらを修正してみました。
また同じく落ちてしまうかもしれませんがご確認お願いします。

**Comment by tkrworks** [comment]
やはり、「Take a shoot」をタップすると同様の例外で落ちます。

Camera2BasicFragmentのonImageAvailableが呼ばれておらず、mFileが
newされないままCamera2BasicFragmentの853行目でnullになって落ちてるようです。

**Comment by tkrworks** [comment]
Android 6.0では再現せず、7.0以降で起きます。

**Comment by nariakiiwatani** [comment]
2b5e73615f1c1d2843a192ab204d1050f3e779cd
再現できなかったのですが、修正できたと思います。
たぶんmFileを作るところと使うところとの呼ばれる順序が前後する場合があったものだと思います。

**Comment by tkrworks** [comment]
すいません、クローズし忘れてました。7.0系でも問題無いこと確認しましたのでクローズします。
