### ISSUE TITLE
OutOfMemoryで落ちる

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#29]
再現性は今のところ不明。

TestブランチのMenuFragment内onBindCardHolderで例外発生。

以下、例外部分のコピペ

ーーー
06-02 11:14:18.213 20924-20924/com.jins_meme.bridge E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: com.jins_meme.bridge, PID: 20924
                                                                      java.lang.OutOfMemoryError: Failed to allocate a 35738508 byte allocation with 16777216 free bytes and 26MB until OOM
                                                                          at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                          at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
                                                                          at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
                                                                          at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
                                                                          at android.graphics.drawable.Drawable.createFromResourceStream(Drawable.java:1152)
                                                                          at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:724)
                                                                          at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:575)
                                                                          at android.content.res.Resources.getDrawable(Resources.java:767)
                                                                          at android.content.Context.getDrawable(Context.java:525)
                                                                          at android.support.v4.content.ContextCompatApi21.getDrawable(ContextCompatApi21.java:30)
                                                                          at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:372)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:202)
                                                                          at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:190)
                                                                          at android.support.v7.content.res.AppCompatResources.getDrawable(AppCompatResources.java:100)
                                                                          at android.support.v7.widget.AppCompatImageHelper.setImageResource(AppCompatImageHelper.java:73)
                                                                          at android.support.v7.widget.AppCompatImageView.setImageResource(AppCompatImageView.java:81)
                                                                          at com.jins_meme.bridge.MenuFragment$MyAdapter.onBindCardHolder(MenuFragment.java:765)
                                                                          at com.jins_meme.bridge.BridgeUIView$Adapter.onBindViewHolder(BridgeUIView.java:164)
                                                                          at com.jins_meme.bridge.BridgeUIView$Adapter.onBindViewHolder(BridgeUIView.java:89)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6356)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6389)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5335)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5598)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5440)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5436)
                                                                          at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2224)
                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1551)
                                                                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1511)
                                                                          at android.support.v7.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1325)
                                                                          at android.support.v7.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1049)
                                                                          at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4722)
                                                                          at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                          at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                          at android.view.Choreographer.doFrame(Choreographer.java:616)
                                                                          at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by nariakiiwatani** [comment]
長時間いろんな操作をした後で突然発生だとしたら、どこかでリークがあって溜まってしまっているということだと思うんですが、発生したときはもしやMeme繋ぎっぱなしで放置でしたか？

**Comment by tkrworks** [comment]
反応遅れてすいません。

起きたときの状況としては、

・Android 7.0
・MEME接続から数分後
・MEMEはかけず、机の上に置いた状態
　（かけていないので、ノイズで勝手に動いていた）

推測ですが、溜まって落ちたというよりも、UIの処理とMEMEの
イベント処理のタイミングによって発生したような感じです。

再現性など、ひきつづき調査します。

**Comment by tkrworks** [comment]
4時間程度、MEMEを接続したままの状態でほったらかしてみたが、
特に問題なし。

**Comment by tkrworks** [comment]
ここのところ発生しないので、一旦解決したとみなしクローズします。
