### ISSUE TITLE
アプリを終了しようとすると落ちる

### ISSUE THREAD

**Issue by nariakiiwatani** [jins-meme/JinsMemeBRIDGE-Android#33]

**Comment by nariakiiwatani** [comment]
2f41cf5454f508fa32f36c46630d988afe2b58b5 で確認

Spotifyに未ログインで試したのが関係あるのかもしれませんが、Spotifyの何かでactivityの破棄に失敗しているようです。

> 06-15 07:49:34.635 23680-23680/com.jins_meme.bridge E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                       Process: com.jins_meme.bridge, PID: 23680
>                                                                       java.lang.RuntimeException: Unable to destroy activity {com.jins_meme.bridge/com.jins_meme.bridge.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.jins_meme.bridge.SpotifyMenuFragment$3@5475cf6
>                                                                           at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3831)
>                                                                           at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849)
>                                                                           at android.app.ActivityThread.-wrap5(ActivityThread.java)
>                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398)
>                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                           at android.os.Looper.loop(Looper.java:148)
>                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                                           at java.lang.reflect.Method.invoke(Native Method)
>                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>                                                                        Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.jins_meme.bridge.SpotifyMenuFragment$3@5475cf6
>                                                                           at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:780)
>                                                                           at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1195)
>                                                                           at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:576)
>                                                                           at com.jins_meme.bridge.SpotifyMenuFragment.destroy(SpotifyMenuFragment.java:220)
>                                                                           at com.jins_meme.bridge.SpotifyMenuFragment.onDestroy(SpotifyMenuFragment.java:236)
>                                                                           at android.support.v4.app.Fragment.performDestroy(Fragment.java:2434)
>                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1442)
>                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
>                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
>                                                                           at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:2951)
>                                                                           at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:271)
>                                                                           at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)
>                                                                           at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
>                                                                           at com.jins_meme.bridge.MainActivity.onDestroy(MainActivity.java:410)
>                                                                           at android.app.Activity.performDestroy(Activity.java:6407)
>                                                                           at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1142)
>                                                                           at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3818)
>                                                                           at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3849) 
>                                                                           at android.app.ActivityThread.-wrap5(ActivityThread.java) 
>                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1398) 
>                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                           at android.os.Looper.loop(Looper.java:148) 
>                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417) 
>                                                                           at java.lang.reflect.Method.invoke(Native Method) 
>                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
> 06-15 07:49:36.503 23680-23680/com.jins_meme.bridge I/Process: Sending signal. PID: 23680 SIG: 9

**Comment by nariakiiwatani** [comment]
`SpotifyMenuFragment.destroy()` の `getActivity().unregisterReceiver(mNetworkStateReceiver);` をコメントアウトしたら正常に終了するようになりましたが、下記のログが表示されます。

> 06-15 07:53:38.090 24175-24175/com.jins_meme.bridge E/ActivityThread: Activity com.jins_meme.bridge.MainActivity has leaked IntentReceiver com.jins_meme.bridge.SpotifyMenuFragment$3@5475cf6 that was originally registered here. Are you missing a call to unregisterReceiver()?
>                                                                       android.app.IntentReceiverLeaked: Activity com.jins_meme.bridge.MainActivity has leaked IntentReceiver com.jins_meme.bridge.SpotifyMenuFragment$3@5475cf6 that was originally registered here. Are you missing a call to unregisterReceiver()?
>                                                                           at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:918)
>                                                                           at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:719)
>                                                                           at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1172)
>                                                                           at android.app.ContextImpl.registerReceiver(ContextImpl.java:1152)
>                                                                           at android.app.ContextImpl.registerReceiver(ContextImpl.java:1146)
>                                                                           at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:554)
>                                                                           at com.jins_meme.bridge.SpotifyMenuFragment.onViewCreated(SpotifyMenuFragment.java:205)
>                                                                           at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
>                                                                           at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
>                                                                           at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:753)
>                                                                           at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
>                                                                           at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
>                                                                           at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
>                                                                           at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
>                                                                           at android.support.v4.app.FragmentController.execPendingActions(FragmentController.java:388)
>                                                                           at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:607)
>                                                                           at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
>                                                                           at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
>                                                                           at android.app.Activity.performStart(Activity.java:6253)
>                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
>                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
>                                                                           at android.app.ActivityThread.-wrap11(ActivityThread.java)
>                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
>                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                           at android.os.Looper.loop(Looper.java:148)
>                                                                           at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                                           at java.lang.reflect.Method.invoke(Native Method)
>                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>
