### ISSUE TITLE
IRKitの設定を開こうとすると落ちる

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#35]
IRKit未接続だからかもしれませんが、ActionBarからIRKitを
タップすると落ちました。

下記、落ちたときの例外ですー。

Process: com.jins_meme.bridge, PID: 14478
                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
                                                                          at com.jins_meme.bridge.RemoConfigFragment.onViewCreated(RemoConfigFragment.java:423)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1314)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                                          at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                                          at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:758)
                                                                          at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2363)
                                                                          at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2149)
                                                                          at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2103)
                                                                          at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2013)
                                                                          at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:710)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6123)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)

**Comment by tkrworks** [comment]
修正を確認したので、クローズします。
