### ISSUE TITLE
カメラのFRONT/REARを連続タップで落ちる。

### ISSUE THREAD

**Issue by tkrworks** [jins-meme/JinsMemeBRIDGE-Android#45]
FRONT/REARのカードを連続してタップしまくるとアプリが落ちる。
以下、落ちたときのExceptionです。

06-21 10:25:44.283 31009-32160/com.jins_meme.bridge E/AndroidRuntime: FATAL EXCEPTION: CameraBackground
                                                                      Process: com.jins_meme.bridge, PID: 31009
                                                                      java.lang.IllegalStateException: CameraDevice was already closed
                                                                          at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:1986)
                                                                          at android.hardware.camera2.impl.CameraDeviceImpl.submitCaptureRequest(CameraDeviceImpl.java:857)
                                                                          at android.hardware.camera2.impl.CameraDeviceImpl.setRepeatingRequest(CameraDeviceImpl.java:904)
                                                                          at android.hardware.camera2.impl.CameraCaptureSessionImpl.setRepeatingRequest(CameraCaptureSessionImpl.java:236)
                                                                          at com.example.android.camera2basic.Camera2BasicFragment$6.onConfigured(Camera2BasicFragment.java:747)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at android.hardware.camera2.dispatch.InvokeDispatcher.dispatch(InvokeDispatcher.java:39)
                                                                          at android.hardware.camera2.dispatch.HandlerDispatcher$1.run(HandlerDispatcher.java:65)
                                                                          at android.os.Handler.handleCallback(Handler.java:751)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by nariakiiwatani** [comment]
92aeca88cf7a8d37eafb3eee4df013b4c78f1c57
修正しました。切り替え処理中はカメラを操作できないようにしています。

**Comment by tkrworks** [comment]
ありがとうございます。落ちないこと確認出来ましたので、クローズします。
